-- ============================
-- ORGANIZAÇÃO / NÚCLEO
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.EMPRESA
  ADD CONSTRAINT FK_EMPRESA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.UNIDADE
  ADD CONSTRAINT FK_UNIDADE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_UNIDADE_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES PEOPLE_FLOW_RH.EMPRESA(ID);

ALTER TABLE PEOPLE_FLOW_RH.DEPARTAMENTO
  ADD CONSTRAINT FK_DEPARTAMENTO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_DEPARTAMENTO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES PEOPLE_FLOW_RH.EMPRESA(ID),
  ADD CONSTRAINT FK_DEPARTAMENTO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES PEOPLE_FLOW_RH.UNIDADE(ID);

ALTER TABLE PEOPLE_FLOW_RH.CENTRO_CUSTO
  ADD CONSTRAINT FK_CENTROCUSTO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

-- ============================
-- PESSOAS / CONTRATOS
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
  ADD CONSTRAINT FK_COLAB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_COLAB_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES PEOPLE_FLOW_RH.EMPRESA(ID),
  ADD CONSTRAINT FK_COLAB_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES PEOPLE_FLOW_RH.DEPARTAMENTO(ID) ON DELETE SET NULL,
  ADD CONSTRAINT FK_COLAB_CENTRO_CUSTO FOREIGN KEY (CENTRO_CUSTO_ID) REFERENCES PEOPLE_FLOW_RH.CENTRO_CUSTO(ID) ON DELETE SET NULL,
  ADD CONSTRAINT FK_COLAB_CARGO FOREIGN KEY (CARGO_ID) REFERENCES PEOPLE_FLOW_RH.CARGO(ID) ON DELETE SET NULL;

ALTER TABLE PEOPLE_FLOW_RH.DEPENDENTE
  ADD CONSTRAINT FK_DEP_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_DEP_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID) ON DELETE CASCADE;

ALTER TABLE PEOPLE_FLOW_RH.CONTA_BANCARIA
  ADD CONSTRAINT FK_CB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_CB_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID) ON DELETE CASCADE;

ALTER TABLE PEOPLE_FLOW_RH.JORNADA_TRABALHO
  ADD CONSTRAINT FK_JORNADA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.CARGO
  ADD CONSTRAINT FK_CARGO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.FAIXA_SALARIAL
  ADD CONSTRAINT FK_FAIXA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_FAIXA_CARGO FOREIGN KEY (CARGO_ID) REFERENCES PEOPLE_FLOW_RH.CARGO(ID);

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR_CARGO
  ADD CONSTRAINT FK_COLABCARGO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_COLABCARGO_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID),
  ADD CONSTRAINT FK_COLABCARGO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES PEOPLE_FLOW_RH.CARGO(ID),
  ADD CONSTRAINT FK_COLABCARGO_CENTROCUSTO FOREIGN KEY (CENTRO_CUSTO_ID) REFERENCES PEOPLE_FLOW_RH.CENTRO_CUSTO(ID);

ALTER TABLE PEOPLE_FLOW_RH.CONTRATO
  ADD CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_CONTRATO_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID),
  ADD CONSTRAINT FK_CONTRATO_JORNADA FOREIGN KEY (JORNADA_ID) REFERENCES PEOPLE_FLOW_RH.JORNADA_TRABALHO(ID),
  ADD CONSTRAINT FK_CONTRATO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES PEOPLE_FLOW_RH.CARGO(ID);

-- ============================
-- PONTO
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.MARCACAO_PONTO
  ADD CONSTRAINT FK_MP_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_MP_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

ALTER TABLE PEOPLE_FLOW_RH.CALCULO_PONTO_DIA
  ADD CONSTRAINT FK_CPD_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_CPD_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

ALTER TABLE PEOPLE_FLOW_RH.AUSENCIA
  ADD CONSTRAINT FK_AUS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_AUS_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

-- ============================
-- FÉRIAS
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.FERIAS_SOLICITACAO
  ADD CONSTRAINT FK_FS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_FS_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_APROVACAO
  ADD CONSTRAINT FK_FA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_FA_SOL FOREIGN KEY (SOLICITACAO_ID) REFERENCES PEOPLE_FLOW_RH.FERIAS_SOLICITACAO(ID);
  -- APROVADOR_USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_SALDO
  ADD CONSTRAINT FK_FSALDO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_FSALDO_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

-- ============================
-- BENEFÍCIOS
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.PLANO_BENEFICIO
  ADD CONSTRAINT FK_PB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.ADESAO_BENEFICIO
  ADD CONSTRAINT FK_AB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_AB_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID),
  ADD CONSTRAINT FK_AB_PLANO FOREIGN KEY (PLANO_ID) REFERENCES PEOPLE_FLOW_RH.PLANO_BENEFICIO(ID);

-- ============================
-- RECRUTAMENTO
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.VAGA
  ADD CONSTRAINT FK_VAGA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_VAGA_DEP FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES PEOPLE_FLOW_RH.DEPARTAMENTO(ID);

ALTER TABLE PEOPLE_FLOW_RH.CANDIDATO
  ADD CONSTRAINT FK_CAND_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.CANDIDATURA
  ADD CONSTRAINT FK_CANDD_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_CANDD_VAGA FOREIGN KEY (VAGA_ID) REFERENCES PEOPLE_FLOW_RH.VAGA(ID),
  ADD CONSTRAINT FK_CANDD_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES PEOPLE_FLOW_RH.CANDIDATO(ID);

ALTER TABLE PEOPLE_FLOW_RH.ENTREVISTA
  ADD CONSTRAINT FK_ENT_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_ENT_CANDD FOREIGN KEY (CANDIDATURA_ID) REFERENCES PEOPLE_FLOW_RH.CANDIDATURA(ID);
  -- ENTREVISTADOR_USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

-- ============================
-- DESEMPENHO & OKR & PDI
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.CICLO_DESEMPENHO
  ADD CONSTRAINT FK_CD_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.AVALIACAO_DESEMPENHO
  ADD CONSTRAINT FK_AD_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_AD_CICLO FOREIGN KEY (CICLO_ID) REFERENCES PEOPLE_FLOW_RH.CICLO_DESEMPENHO(ID),
  ADD CONSTRAINT FK_AD_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);
  -- AVALIADOR_USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

ALTER TABLE PEOPLE_FLOW_RH.OKR
  ADD CONSTRAINT FK_OKR_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);
  -- RESPONSAVEL_USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

ALTER TABLE PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE
  ADD CONSTRAINT FK_OKRRC_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_OKRRC_OKR FOREIGN KEY (OKR_ID) REFERENCES PEOPLE_FLOW_RH.OKR(ID);

ALTER TABLE PEOPLE_FLOW_RH.OKR_CHECKIN
  ADD CONSTRAINT FK_OKRC_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_OKRC_RESULTADO FOREIGN KEY (RESULTADO_CHAVE_ID) REFERENCES PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE(ID);
  -- USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

ALTER TABLE PEOPLE_FLOW_RH.PDI
  ADD CONSTRAINT FK_PDI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_PDI_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID),
  ADD CONSTRAINT FK_PDI_CICLO FOREIGN KEY (CICLO_ID) REFERENCES PEOPLE_FLOW_RH.CICLO_DESEMPENHO(ID);

ALTER TABLE PEOPLE_FLOW_RH.COMPETENCIA_CARGO
  ADD CONSTRAINT FK_COMPCARGO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_COMPCARGO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES PEOPLE_FLOW_RH.CARGO(ID);

-- ============================
-- REEMBOLSOS
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.POLITICA_REEMBOLSO
  ADD CONSTRAINT FK_PR_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO
  ADD CONSTRAINT FK_RS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_RS_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_ITEM
  ADD CONSTRAINT FK_RI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_RI_SOL FOREIGN KEY (SOLICITACAO_ID) REFERENCES PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO(ID);

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_APROVACAO
  ADD CONSTRAINT FK_RA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_RA_SOL FOREIGN KEY (SOLICITACAO_ID) REFERENCES PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO(ID);
  -- APROVADOR_USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

-- ============================
-- FOLHA
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.RUBRICA
  ADD CONSTRAINT FK_RUB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.FOLHA_EXECUCAO
  ADD CONSTRAINT FK_FE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.FOLHA_ITEM
  ADD CONSTRAINT FK_FI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_FI_EXECUCAO FOREIGN KEY (EXECUCAO_ID) REFERENCES PEOPLE_FLOW_RH.FOLHA_EXECUCAO(ID),
  ADD CONSTRAINT FK_FI_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID),
  ADD CONSTRAINT FK_FI_RUBRICA FOREIGN KEY (RUBRICA_ID) REFERENCES PEOPLE_FLOW_RH.RUBRICA(ID);

-- ============================
-- ESOCIAL
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.EVENTO_ESOCIAL
  ADD CONSTRAINT FK_ESOCIAL_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.PAYLOAD_ESOCIAL
  ADD CONSTRAINT FK_PESOCIAL_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES PEOPLE_FLOW_RH.EVENTO_ESOCIAL(ID);

-- ============================
-- WORKFLOW
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.DEFINICAO_WORKFLOW
  ADD CONSTRAINT FK_DW_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.INSTANCIA_WORKFLOW
  ADD CONSTRAINT FK_IW_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_IW_DEFINICAO FOREIGN KEY (DEFINICAO_ID) REFERENCES PEOPLE_FLOW_RH.DEFINICAO_WORKFLOW(ID);

ALTER TABLE PEOPLE_FLOW_RH.TAREFA_WORKFLOW
  ADD CONSTRAINT FK_TW_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_TW_INSTANCIA FOREIGN KEY (INSTANCIA_ID) REFERENCES PEOPLE_FLOW_RH.INSTANCIA_WORKFLOW(ID);
  -- RESPONSAVEL_USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

ALTER TABLE PEOPLE_FLOW_RH.LOG_WORKFLOW
  ADD CONSTRAINT FK_LW_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_LW_INSTANCIA FOREIGN KEY (INSTANCIA_ID) REFERENCES PEOPLE_FLOW_RH.INSTANCIA_WORKFLOW(ID);

-- ============================
-- NOTIFICAÇÕES
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.TEMPLATE_NOTIFICACAO
  ADD CONSTRAINT FK_TMP_NOTIF_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID);

ALTER TABLE PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO
  ADD CONSTRAINT FK_NE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_NE_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES PEOPLE_FLOW_RH.TEMPLATE_NOTIFICACAO(ID),
  ADD CONSTRAINT FK_NE_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);
  -- USUARIO_ID armazena UUID do Keycloak diretamente (sem FK)

ALTER TABLE PEOPLE_FLOW_RH.DOCUMENTO_COLABORADOR
  ADD CONSTRAINT FK_DOC_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_DOC_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

-- ============================
-- SAÚDE OCUPACIONAL
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.ASO
  ADD CONSTRAINT FK_ASO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_ASO_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID),
  ADD CONSTRAINT FK_ASO_DOC FOREIGN KEY (DOCUMENTO_ID) REFERENCES PEOPLE_FLOW_RH.DOCUMENTO_COLABORADOR(ID);

ALTER TABLE PEOPLE_FLOW_RH.EXAME_AGENDAMENTO
  ADD CONSTRAINT FK_EXAME_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES PEOPLE_FLOW_RH.CLIENTE(ID),
  ADD CONSTRAINT FK_EXAME_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES PEOPLE_FLOW_RH.COLABORADOR(ID);

-- ============================
-- KEYCLOAK ACCESS CONTROL
-- ============================
ALTER TABLE PEOPLE_FLOW_RH.CARGO_ROLE
  ADD CONSTRAINT FK_CARGO_ROLE_CARGO FOREIGN KEY (CARGO_ID) REFERENCES PEOPLE_FLOW_RH.CARGO(ID) ON DELETE CASCADE;

ALTER TABLE PEOPLE_FLOW_RH.DEPARTAMENTO_GRUPO
  ADD CONSTRAINT FK_DEPT_GRUPO_DEPT FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES PEOPLE_FLOW_RH.DEPARTAMENTO(ID) ON DELETE CASCADE;