-- ============================
-- ÍNDICES ÚNICOS DE INTEGRIDADE
-- ============================

-- Colaborador
CREATE UNIQUE INDEX IF NOT EXISTS UQ_COLABORADOR_CPF
    ON PEOPLE_FLOW_RH.COLABORADOR (CLIENTE_ID, CPF)
    WHERE CPF IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS UQ_COLABORADOR_MATRICULA
    ON PEOPLE_FLOW_RH.COLABORADOR (EMPRESA_ID, MATRICULA)
    WHERE MATRICULA IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS UQ_COLABORADOR_EMAIL
    ON PEOPLE_FLOW_RH.COLABORADOR (CLIENTE_ID, EMAIL)
    WHERE EMAIL IS NOT NULL;

-- Empresa
CREATE UNIQUE INDEX IF NOT EXISTS UQ_EMPRESA_CNPJ
    ON PEOPLE_FLOW_RH.EMPRESA (CLIENTE_ID, CNPJ);

-- NOTA: Tabela USUARIO foi removida - dados de usuários vêm diretamente do Keycloak

-- Candidato
CREATE UNIQUE INDEX IF NOT EXISTS UQ_CANDIDATO_CPF
    ON PEOPLE_FLOW_RH.CANDIDATO (CLIENTE_ID, CPF);

-- ============================
-- ÍNDICES PARA BUSCA (FKs)
-- ============================

-- Organização
CREATE INDEX IF NOT EXISTS IDX_EMPRESA_CLIENTE ON PEOPLE_FLOW_RH.EMPRESA(CLIENTE_ID);
CREATE INDEX IF NOT EXISTS IDX_UNIDADE_EMPRESA ON PEOPLE_FLOW_RH.UNIDADE(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_DEPARTAMENTO_EMPRESA ON PEOPLE_FLOW_RH.DEPARTAMENTO(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_DEPARTAMENTO_UNIDADE ON PEOPLE_FLOW_RH.DEPARTAMENTO(UNIDADE_ID);

-- Segurança
-- Índices de USUARIO removidos (tabela não existe mais)

-- Pessoas / Contratos
CREATE INDEX IF NOT EXISTS IDX_COLAB_EMPRESA ON PEOPLE_FLOW_RH.COLABORADOR(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_COLAB_DEPARTAMENTO ON PEOPLE_FLOW_RH.COLABORADOR(DEPARTAMENTO_ID);
CREATE INDEX IF NOT EXISTS IDX_COLAB_CENTROCUSTO ON PEOPLE_FLOW_RH.COLABORADOR(CENTRO_CUSTO_ID);

CREATE INDEX IF NOT EXISTS IDX_DEPENDENTE_COLAB ON PEOPLE_FLOW_RH.DEPENDENTE(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_CB_COLAB ON PEOPLE_FLOW_RH.CONTA_BANCARIA(COLABORADOR_ID);

CREATE INDEX IF NOT EXISTS IDX_CONTRATO_COLAB ON PEOPLE_FLOW_RH.CONTRATO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_CONTRATO_CARGO ON PEOPLE_FLOW_RH.CONTRATO(CARGO_ID);

CREATE INDEX IF NOT EXISTS IDX_COLABCARGO_COLAB ON PEOPLE_FLOW_RH.COLABORADOR_CARGO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_COLABCARGO_CARGO ON PEOPLE_FLOW_RH.COLABORADOR_CARGO(CARGO_ID);

-- Ponto
CREATE INDEX IF NOT EXISTS IDX_MP_COLAB_DATA ON PEOPLE_FLOW_RH.MARCACAO_PONTO(COLABORADOR_ID, DATA_HORA);
CREATE INDEX IF NOT EXISTS IDX_CPD_COLAB_DATA ON PEOPLE_FLOW_RH.CALCULO_PONTO_DIA(COLABORADOR_ID, DATA);
CREATE INDEX IF NOT EXISTS IDX_AUS_COLAB_DATA ON PEOPLE_FLOW_RH.AUSENCIA(COLABORADOR_ID, INICIO, FIM);

-- Férias
CREATE INDEX IF NOT EXISTS IDX_FS_COLAB ON PEOPLE_FLOW_RH.FERIAS_SOLICITACAO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_FA_SOL ON PEOPLE_FLOW_RH.FERIAS_APROVACAO(SOLICITACAO_ID);

-- Benefícios
CREATE INDEX IF NOT EXISTS IDX_AB_COLAB ON PEOPLE_FLOW_RH.ADESAO_BENEFICIO(COLABORADOR_ID);

-- Recrutamento
CREATE INDEX IF NOT EXISTS IDX_CANDD_VAGA ON PEOPLE_FLOW_RH.CANDIDATURA(VAGA_ID);
CREATE INDEX IF NOT EXISTS IDX_CANDD_CAND ON PEOPLE_FLOW_RH.CANDIDATURA(CANDIDATO_ID);
CREATE INDEX IF NOT EXISTS IDX_ENT_CANDD ON PEOPLE_FLOW_RH.ENTREVISTA(CANDIDATURA_ID);

-- Desempenho / OKR
CREATE INDEX IF NOT EXISTS IDX_AD_COLAB ON PEOPLE_FLOW_RH.AVALIACAO_DESEMPENHO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_OKRRC_OKR ON PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE(OKR_ID);
CREATE INDEX IF NOT EXISTS IDX_OKRC_RESULTADO ON PEOPLE_FLOW_RH.OKR_CHECKIN(RESULTADO_CHAVE_ID);

CREATE INDEX IF NOT EXISTS IDX_PDI_COLAB ON PEOPLE_FLOW_RH.PDI(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_COMP_CARGO ON PEOPLE_FLOW_RH.COMPETENCIA_CARGO(CARGO_ID);

-- Reembolsos
CREATE INDEX IF NOT EXISTS IDX_RS_COLAB ON PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_RI_SOL ON PEOPLE_FLOW_RH.REEMBOLSO_ITEM(SOLICITACAO_ID);

-- Folha
CREATE INDEX IF NOT EXISTS IDX_FI_EXECUCAO ON PEOPLE_FLOW_RH.FOLHA_ITEM(EXECUCAO_ID);
CREATE INDEX IF NOT EXISTS IDX_FI_COLAB ON PEOPLE_FLOW_RH.FOLHA_ITEM(COLABORADOR_ID);

-- eSocial
CREATE INDEX IF NOT EXISTS IDX_PESOCIAL_EVENTO ON PEOPLE_FLOW_RH.PAYLOAD_ESOCIAL(EVENTO_ID);

-- Workflow
CREATE INDEX IF NOT EXISTS IDX_IW_DEFINICAO ON PEOPLE_FLOW_RH.INSTANCIA_WORKFLOW(DEFINICAO_ID);
CREATE INDEX IF NOT EXISTS IDX_TW_INSTANCIA ON PEOPLE_FLOW_RH.TAREFA_WORKFLOW(INSTANCIA_ID);
CREATE INDEX IF NOT EXISTS IDX_LW_INSTANCIA ON PEOPLE_FLOW_RH.LOG_WORKFLOW(INSTANCIA_ID);

-- ============================
-- ÍNDICES PARA COLUNAS *_USUARIO_ID (KEYCLOAK UUID)
-- ============================

-- Férias
CREATE INDEX IF NOT EXISTS IDX_FA_APROVADOR 
    ON PEOPLE_FLOW_RH.FERIAS_APROVACAO(APROVADOR_USUARIO_ID);

-- Entrevistas
CREATE INDEX IF NOT EXISTS IDX_ENT_ENTREVISTADOR 
    ON PEOPLE_FLOW_RH.ENTREVISTA(ENTREVISTADOR_USUARIO_ID);

-- Avaliação de Desempenho
CREATE INDEX IF NOT EXISTS IDX_AD_AVALIADOR 
    ON PEOPLE_FLOW_RH.AVALIACAO_DESEMPENHO(AVALIADOR_USUARIO_ID);

-- OKR
CREATE INDEX IF NOT EXISTS IDX_OKR_RESPONSAVEL 
    ON PEOPLE_FLOW_RH.OKR(RESPONSAVEL_USUARIO_ID) 
    WHERE RESPONSAVEL_USUARIO_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IDX_OKRC_USUARIO 
    ON PEOPLE_FLOW_RH.OKR_CHECKIN(USUARIO_ID) 
    WHERE USUARIO_ID IS NOT NULL;

-- Reembolsos
CREATE INDEX IF NOT EXISTS IDX_RA_APROVADOR 
    ON PEOPLE_FLOW_RH.REEMBOLSO_APROVACAO(APROVADOR_USUARIO_ID);

-- Workflow
CREATE INDEX IF NOT EXISTS IDX_TW_RESPONSAVEL 
    ON PEOPLE_FLOW_RH.TAREFA_WORKFLOW(RESPONSAVEL_USUARIO_ID) 
    WHERE RESPONSAVEL_USUARIO_ID IS NOT NULL;

-- Auditoria
CREATE INDEX IF NOT EXISTS IDX_EA_USUARIO 
    ON PEOPLE_FLOW_RH.EVENTO_AUDITORIA(USUARIO_ID) 
    WHERE USUARIO_ID IS NOT NULL;

-- Notificações
CREATE INDEX IF NOT EXISTS IDX_NE_TEMPLATE ON PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO(TEMPLATE_ID);
CREATE INDEX IF NOT EXISTS IDX_NE_USUARIO 
    ON PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO(USUARIO_ID) 
    WHERE USUARIO_ID IS NOT NULL;
CREATE INDEX IF NOT EXISTS IDX_NE_COLAB ON PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO(COLABORADOR_ID);

-- Saúde Ocupacional
CREATE INDEX IF NOT EXISTS IDX_ASO_COLAB ON PEOPLE_FLOW_RH.ASO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_EXAME_COLAB ON PEOPLE_FLOW_RH.EXAME_AGENDAMENTO(COLABORADOR_ID);

-- ============================
-- ============================
-- ÍNDICES PARA FKs FREQUENTES (PERFORMANCE)
-- ============================

-- Colaborador
CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_DEPARTAMENTO 
    ON PEOPLE_FLOW_RH.COLABORADOR(DEPARTAMENTO_ID) 
    WHERE DEPARTAMENTO_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_CENTRO_CUSTO 
    ON PEOPLE_FLOW_RH.COLABORADOR(CENTRO_CUSTO_ID) 
    WHERE CENTRO_CUSTO_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_STATUS 
    ON PEOPLE_FLOW_RH.COLABORADOR(STATUS);

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_EMPRESA 
    ON PEOPLE_FLOW_RH.COLABORADOR(EMPRESA_ID);

-- Índices para queries de data
CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_DATA_ADMISSAO 
    ON PEOPLE_FLOW_RH.COLABORADOR(DATA_ADMISSAO) 
    WHERE DATA_ADMISSAO IS NOT NULL;

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_DATA_DEMISSAO 
    ON PEOPLE_FLOW_RH.COLABORADOR(DATA_DEMISSAO) 
    WHERE DATA_DEMISSAO IS NOT NULL;

-- ============================
-- ÍNDICES COMPOSTOS PARA QUERIES COMUNS
-- ============================

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_CLIENTE_STATUS 
    ON PEOPLE_FLOW_RH.COLABORADOR(CLIENTE_ID, STATUS) 
    WHERE EXCLUIDO_EM IS NULL;

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_EMPRESA_STATUS 
    ON PEOPLE_FLOW_RH.COLABORADOR(EMPRESA_ID, STATUS) 
    WHERE EXCLUIDO_EM IS NULL;

CREATE INDEX IF NOT EXISTS IDX_FERIAS_COLAB_STATUS 
    ON PEOPLE_FLOW_RH.FERIAS_SOLICITACAO(COLABORADOR_ID, STATUS);

-- ============================
-- ÍNDICES PARCIAIS PARA SOFT DELETE (PERFORMANCE)
-- ============================

CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_ATIVO 
    ON PEOPLE_FLOW_RH.COLABORADOR(CLIENTE_ID) 
    WHERE EXCLUIDO_EM IS NULL;

CREATE INDEX IF NOT EXISTS IDX_EMPRESA_ATIVA 
    ON PEOPLE_FLOW_RH.EMPRESA(CLIENTE_ID) 
    WHERE EXCLUIDO_EM IS NULL;

CREATE INDEX IF NOT EXISTS IDX_DEPARTAMENTO_ATIVO 
    ON PEOPLE_FLOW_RH.DEPARTAMENTO(CLIENTE_ID, EMPRESA_ID) 
    WHERE EXCLUIDO_EM IS NULL;

-- ============================
-- KEYCLOAK ACCESS CONTROL
-- ============================

-- Índice único para garantir relação 1:1 entre colaborador e usuário Keycloak
CREATE UNIQUE INDEX IF NOT EXISTS UQ_COLABORADOR_KEYCLOAK_USER
    ON PEOPLE_FLOW_RH.COLABORADOR (KEYCLOAK_USER_ID)
    WHERE KEYCLOAK_USER_ID IS NOT NULL;

-- Índice para busca reversa (Keycloak → Colaborador)
CREATE INDEX IF NOT EXISTS IDX_COLABORADOR_KEYCLOAK_LOOKUP
    ON PEOPLE_FLOW_RH.COLABORADOR (KEYCLOAK_USER_ID)
    WHERE KEYCLOAK_USER_ID IS NOT NULL;

-- Índice para busca de roles por cargo
CREATE INDEX IF NOT EXISTS IDX_CARGO_ROLE_CARGO
    ON PEOPLE_FLOW_RH.CARGO_ROLE(CARGO_ID);

-- Índice único para busca reversa de grupo por Keycloak ID
CREATE UNIQUE INDEX IF NOT EXISTS UQ_DEPT_GRUPO_KEYCLOAK_ID
    ON PEOPLE_FLOW_RH.DEPARTAMENTO_GRUPO(KEYCLOAK_GROUP_ID);

