-- ============================
-- SEQUENCES - OTIMIZAÇÃO E CONTROLE
-- ============================
-- 
-- Este arquivo configura as sequences criadas automaticamente pelo IDENTITY.
-- 
-- Quando você usa 'GENERATED BY DEFAULT AS IDENTITY', o PostgreSQL cria
-- automaticamente uma sequence com o nome: <tabela>_id_seq
-- 
-- Aqui otimizamos essas sequences para melhor performance através do CACHE.
-- 
-- CACHE: Número de valores pré-alocados em memória (reduz IO)
--   - 20:  Volume normal de inserções
--   - 50:  Volume médio de inserções
--   - 100: Alto volume de inserções (logs, marcações)
--

COMMENT ON TABLE PEOPLE_FLOW_RH.EMPRESA IS 
'Empresa principal do sistema.';

ALTER SEQUENCE PEOPLE_FLOW_RH.EMPRESA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.UNIDADE_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.DEPARTAMENTO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.CENTRO_CUSTO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- NOTA: Tabela USUARIO foi removida - dados vêm do Keycloak
-- ============================

-- ============================
-- PESSOAS / COLABORADORES
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.COLABORADOR_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 50
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.DEPENDENTE_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.CONTA_BANCARIA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- JORNADA & CARGOS
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.JORNADA_TRABALHO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.CARGO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.FAIXA_SALARIAL_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.COLABORADOR_CARGO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- CONTRATOS
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.CONTRATO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- PONTO
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.MARCACAO_PONTO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 100
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.CALCULO_PONTO_DIA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.AUSENCIA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- FÉRIAS
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.FERIAS_SOLICITACAO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.FERIAS_APROVACAO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.FERIAS_SALDO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- BENEFÍCIOS
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.PLANO_BENEFICIO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.ADESAO_BENEFICIO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- RECRUTAMENTO
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.VAGA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.CANDIDATO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.CANDIDATURA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.ENTREVISTA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- DESEMPENHO
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.CICLO_DESEMPENHO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.AVALIACAO_DESEMPENHO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- OKR
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.OKR_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.OKR_CHECKIN_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- PDI & COMPETÊNCIAS
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.PDI_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.COMPETENCIA_CARGO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- REEMBOLSOS
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.POLITICA_REEMBOLSO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.REEMBOLSO_ITEM_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.REEMBOLSO_APROVACAO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- FOLHA DE PAGAMENTO
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.RUBRICA_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.FOLHA_EXECUCAO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.FOLHA_ITEM_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 50
    NO CYCLE;

-- ============================
-- ESOCIAL
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.EVENTO_ESOCIAL_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.PAYLOAD_ESOCIAL_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- WORKFLOW
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.DEFINICAO_WORKFLOW_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.INSTANCIA_WORKFLOW_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.TAREFA_WORKFLOW_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.LOG_WORKFLOW_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 100
    NO CYCLE;


-- ============================
-- NOTIFICAÇÕES
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.TEMPLATE_NOTIFICACAO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 50
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.DOCUMENTO_COLABORADOR_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- SAÚDE OCUPACIONAL
-- ============================

ALTER SEQUENCE PEOPLE_FLOW_RH.ASO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

ALTER SEQUENCE PEOPLE_FLOW_RH.EXAME_AGENDAMENTO_ID_SEQ
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 20
    NO CYCLE;

-- ============================
-- SCRIPTS ÚTEIS PARA GERENCIAMENTO
-- ============================

-- Ver todas as sequences e seus valores atuais:
-- SELECT 
--     schemaname,
--     sequencename,
--     last_value,
--     increment_by,
--     max_value,
--     cache_size
-- FROM pg_sequences
-- WHERE schemaname = 'people_flow_rh'
-- ORDER BY sequencename;

-- Resetar uma sequence específica (exemplo):
-- SELECT setval('people_flow_rh.empresa_id_seq', 1, false);

-- Resetar sequence para o próximo valor após o último ID usado:
-- SELECT setval('people_flow_rh.empresa_id_seq', 
--               (SELECT COALESCE(MAX(id), 0) + 1 FROM people_flow_rh.empresa), 
--               false);

-- Ver uso de sequences (queries ativas):
-- SELECT 
--     c.relname as sequence_name,
--     pg_stat_get_numscans(c.oid) as scans
-- FROM pg_class c
-- WHERE c.relkind = 'S'
--   AND c.relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'people_flow_rh')
-- ORDER BY scans DESC;

-- Resetar TODAS as sequences (CUIDADO! Usar apenas em desenvolvimento):
-- DO $$
-- DECLARE
--     seq_record RECORD;
-- BEGIN
--     FOR seq_record IN 
--         SELECT schemaname, sequencename 
--         FROM pg_sequences 
--         WHERE schemaname = 'people_flow_rh'
--     LOOP
--         EXECUTE format('SELECT setval(%L, 1, false)', 
--                       seq_record.schemaname || '.' || seq_record.sequencename);
--     END LOOP;
-- END $$;

