-- ============================
-- CHECK CONSTRAINTS E VALIDAÇÕES
-- ============================
--
-- Este arquivo adiciona validações de integridade de dados através de:
-- - CHECK constraints para valores permitidos
-- - Validações de formato (CPF, CNPJ, Email)
-- - Validações de range (valores >= 0, datas início < fim)
-- - Validações de tamanho
--

-- ============================
-- ORGANIZAÇÃO / NÚCLEO
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.CLIENTE
    ADD CONSTRAINT CHK_CLIENTE_STATUS CHECK (STATUS IN ('ativo', 'inativo', 'suspenso'));

ALTER TABLE PEOPLE_FLOW_RH.CLIENTE
    ADD CONSTRAINT CHK_CLIENTE_CNPJ_LENGTH CHECK (CNPJ IS NULL OR LENGTH(CNPJ) = 18);

-- ============================
-- PESSOAS / COLABORADORES
-- ============================

-- Validações de COLABORADOR já existem acima (CHK_COLABORADOR_DATAS, etc.)

-- ============================
-- JORNADA & CARGOS
-- ============================
-- Validação de FAIXA_SALARIAL já existe acima (CHK_FAIXA_MIN_MAX)

-- ============================
-- FÉRIAS
-- ============================
-- Validação de FERIAS_SOLICITACAO já existe acima

-- ============================
-- CONTRATOS
-- ============================
-- Validação de CONTRATO já existe acima (CHK_CONTRATO_DATAS)

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
    ADD CONSTRAINT CHK_COLABORADOR_STATUS CHECK (STATUS IN ('ativo', 'inativo', 'afastado', 'demitido', 'aposentado'));

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
    ADD CONSTRAINT CHK_COLABORADOR_CPF_LENGTH CHECK (CPF IS NULL OR LENGTH(CPF) = 14);

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
    ADD CONSTRAINT CHK_COLABORADOR_DATAS CHECK (DATA_DEMISSAO IS NULL OR DATA_DEMISSAO >= DATA_ADMISSAO);

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
    ADD CONSTRAINT CHK_COLABORADOR_EMAIL_FORMAT CHECK (EMAIL IS NULL OR EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

ALTER TABLE PEOPLE_FLOW_RH.DEPENDENTE
    ADD CONSTRAINT CHK_DEPENDENTE_PARENTESCO CHECK (PARENTESCO IN ('conjuge', 'filho', 'filha', 'pai', 'mae', 'outro'));

ALTER TABLE PEOPLE_FLOW_RH.DEPENDENTE
    ADD CONSTRAINT CHK_DEPENDENTE_CPF_LENGTH CHECK (CPF IS NULL OR LENGTH(CPF) = 14);

ALTER TABLE PEOPLE_FLOW_RH.CONTA_BANCARIA
    ADD CONSTRAINT CHK_CONTA_TIPO CHECK (TIPO IS NULL OR TIPO IN ('corrente', 'poupanca', 'salario'));

-- ============================
-- JORNADA & CARGOS
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.JORNADA_TRABALHO
    ADD CONSTRAINT CHK_JORNADA_HORAS CHECK (CARGA_SEMANAL_HORAS IS NULL OR CARGA_SEMANAL_HORAS BETWEEN 0 AND 60);

ALTER TABLE PEOPLE_FLOW_RH.FAIXA_SALARIAL
    ADD CONSTRAINT CHK_FAIXA_MIN_POSITIVO CHECK (FAIXA_MIN >= 0);

ALTER TABLE PEOPLE_FLOW_RH.FAIXA_SALARIAL
    ADD CONSTRAINT CHK_FAIXA_MAX_POSITIVO CHECK (FAIXA_MAX >= 0);

ALTER TABLE PEOPLE_FLOW_RH.FAIXA_SALARIAL
    ADD CONSTRAINT CHK_FAIXA_MIN_MAX CHECK (FAIXA_MAX >= FAIXA_MIN);

ALTER TABLE PEOPLE_FLOW_RH.FAIXA_SALARIAL
    ADD CONSTRAINT CHK_FAIXA_MOEDA CHECK (MOEDA IN ('BRL', 'USD', 'EUR'));

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR_CARGO
    ADD CONSTRAINT CHK_COLABCARGO_SALARIO CHECK (SALARIO IS NULL OR SALARIO >= 0);

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR_CARGO
    ADD CONSTRAINT CHK_COLABCARGO_DATAS CHECK (FIM IS NULL OR FIM >= INICIO);

-- ============================
-- CONTRATOS
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.CONTRATO
    ADD CONSTRAINT CHK_CONTRATO_TIPO CHECK (TIPO IS NULL OR TIPO IN ('CLT', 'PJ', 'estagio', 'temporario', 'intermitente'));

ALTER TABLE PEOPLE_FLOW_RH.CONTRATO
    ADD CONSTRAINT CHK_CONTRATO_REGIME CHECK (REGIME IS NULL OR REGIME IN ('integral', 'parcial', 'horista'));

ALTER TABLE PEOPLE_FLOW_RH.CONTRATO
    ADD CONSTRAINT CHK_CONTRATO_SALARIO CHECK (SALARIO_BASE IS NULL OR SALARIO_BASE >= 0);

ALTER TABLE PEOPLE_FLOW_RH.CONTRATO
    ADD CONSTRAINT CHK_CONTRATO_DATAS CHECK (FIM IS NULL OR FIM >= INICIO);

-- ============================
-- PONTO
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.MARCACAO_PONTO
    ADD CONSTRAINT CHK_MP_TIPO CHECK (TIPO IN ('entrada', 'saida', 'entrada_intervalo', 'saida_intervalo'));

ALTER TABLE PEOPLE_FLOW_RH.MARCACAO_PONTO
    ADD CONSTRAINT CHK_MP_ORIGEM CHECK (ORIGEM IS NULL OR ORIGEM IN ('kiosk', 'mobile', 'web', 'import', 'manual'));

ALTER TABLE PEOPLE_FLOW_RH.MARCACAO_PONTO
    ADD CONSTRAINT CHK_MP_LATITUDE CHECK (LATITUDE IS NULL OR (LATITUDE BETWEEN -90 AND 90));

ALTER TABLE PEOPLE_FLOW_RH.MARCACAO_PONTO
    ADD CONSTRAINT CHK_MP_LONGITUDE CHECK (LONGITUDE IS NULL OR (LONGITUDE BETWEEN -180 AND 180));

ALTER TABLE PEOPLE_FLOW_RH.CALCULO_PONTO_DIA
    ADD CONSTRAINT CHK_CPD_HORAS_TRABALHADAS CHECK (HORAS_TRABALHADAS >= 0);

ALTER TABLE PEOPLE_FLOW_RH.CALCULO_PONTO_DIA
    ADD CONSTRAINT CHK_CPD_HORAS_EXTRAS CHECK (HORAS_EXTRAS >= 0);

ALTER TABLE PEOPLE_FLOW_RH.AUSENCIA
    ADD CONSTRAINT CHK_AUSENCIA_TIPO CHECK (TIPO IN ('atestado', 'falta', 'falta_justificada', 'licenca', 'suspensao'));

ALTER TABLE PEOPLE_FLOW_RH.AUSENCIA
    ADD CONSTRAINT CHK_AUSENCIA_DATAS CHECK (FIM >= INICIO);

-- ============================
-- FÉRIAS
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_SOLICITACAO
    ADD CONSTRAINT CHK_FS_STATUS CHECK (STATUS IN ('pendente', 'aprovada', 'reprovada', 'cancelada'));

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_SOLICITACAO
    ADD CONSTRAINT CHK_FS_DATAS CHECK (FIM >= INICIO);

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_APROVACAO
    ADD CONSTRAINT CHK_FA_STATUS CHECK (STATUS IN ('aprovado', 'reprovado'));

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_SALDO
    ADD CONSTRAINT CHK_FSALDO_DIAS_AQUISITIVOS CHECK (DIAS_AQUISITIVOS >= 0);

ALTER TABLE PEOPLE_FLOW_RH.FERIAS_SALDO
    ADD CONSTRAINT CHK_FSALDO_DIAS_DISPONIVEIS CHECK (DIAS_DISPONIVEIS >= 0);

-- ============================
-- BENEFÍCIOS
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.PLANO_BENEFICIO
    ADD CONSTRAINT CHK_PB_TIPO CHECK (TIPO IN ('VT', 'VR', 'VA', 'saude', 'odonto', 'seguro_vida', 'gym', 'outro'));

ALTER TABLE PEOPLE_FLOW_RH.ADESAO_BENEFICIO
    ADD CONSTRAINT CHK_AB_DATAS CHECK (FIM IS NULL OR FIM >= INICIO);

ALTER TABLE PEOPLE_FLOW_RH.ADESAO_BENEFICIO
    ADD CONSTRAINT CHK_AB_CUSTO_MENSAL CHECK (CUSTO_MENSAL IS NULL OR CUSTO_MENSAL >= 0);

ALTER TABLE PEOPLE_FLOW_RH.ADESAO_BENEFICIO
    ADD CONSTRAINT CHK_AB_COTA_COLABORADOR CHECK (COTA_COLABORADOR IS NULL OR COTA_COLABORADOR >= 0);

-- ============================
-- RECRUTAMENTO
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.VAGA
    ADD CONSTRAINT CHK_VAGA_STATUS CHECK (STATUS IN ('aberta', 'em_andamento', 'suspensa', 'fechada', 'cancelada'));

ALTER TABLE PEOPLE_FLOW_RH.CANDIDATO
    ADD CONSTRAINT CHK_CANDIDATO_CPF_LENGTH CHECK (CPF IS NULL OR LENGTH(CPF) = 14);

ALTER TABLE PEOPLE_FLOW_RH.CANDIDATO
    ADD CONSTRAINT CHK_CANDIDATO_EMAIL_FORMAT CHECK (EMAIL IS NULL OR EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

ALTER TABLE PEOPLE_FLOW_RH.CANDIDATURA
    ADD CONSTRAINT CHK_CANDD_STATUS CHECK (STATUS IN ('em_analise', 'triagem', 'entrevista', 'aprovado', 'reprovado', 'desistente'));

ALTER TABLE PEOPLE_FLOW_RH.ENTREVISTA
    ADD CONSTRAINT CHK_ENT_TIPO CHECK (TIPO IS NULL OR TIPO IN ('triagem', 'tecnica', 'comportamental', 'final', 'online', 'presencial'));

ALTER TABLE PEOPLE_FLOW_RH.ENTREVISTA
    ADD CONSTRAINT CHK_ENT_RESULTADO CHECK (RESULTADO IS NULL OR RESULTADO IN ('aprovado', 'reprovado', 'pendente'));

-- ============================
-- DESEMPENHO
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.CICLO_DESEMPENHO
    ADD CONSTRAINT CHK_CD_DATAS CHECK (FIM >= INICIO);

ALTER TABLE PEOPLE_FLOW_RH.AVALIACAO_DESEMPENHO
    ADD CONSTRAINT CHK_AD_NOTA CHECK (NOTA IS NULL OR NOTA BETWEEN 0 AND 10);

ALTER TABLE PEOPLE_FLOW_RH.AVALIACAO_DESEMPENHO
    ADD CONSTRAINT CHK_AD_STATUS CHECK (STATUS IN ('rascunho', 'em_avaliacao', 'concluida', 'cancelada'));

-- ============================
-- OKR
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.OKR
    ADD CONSTRAINT CHK_OKR_TIPO CHECK (TIPO IN ('organizacional', 'equipe', 'pessoal'));

ALTER TABLE PEOPLE_FLOW_RH.OKR
    ADD CONSTRAINT CHK_OKR_DATAS CHECK (FIM IS NULL OR INICIO IS NULL OR FIM >= INICIO);

ALTER TABLE PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE
    ADD CONSTRAINT CHK_OKRRC_UNIDADE CHECK (UNIDADE IS NULL OR UNIDADE IN ('percentual', 'numero', 'moeda', 'binario'));

ALTER TABLE PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE
    ADD CONSTRAINT CHK_OKRRC_VALOR_ALVO CHECK (VALOR_ALVO IS NULL OR VALOR_ALVO >= 0);

ALTER TABLE PEOPLE_FLOW_RH.OKR_RESULTADO_CHAVE
    ADD CONSTRAINT CHK_OKRRC_VALOR_ATUAL CHECK (VALOR_ATUAL >= 0);

ALTER TABLE PEOPLE_FLOW_RH.OKR_CHECKIN
    ADD CONSTRAINT CHK_OKRC_VALOR CHECK (VALOR IS NULL OR VALOR >= 0);

-- ============================
-- PDI
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.PDI
    ADD CONSTRAINT CHK_PDI_STATUS CHECK (STATUS IN ('aberto', 'em_andamento', 'concluido', 'cancelado'));

ALTER TABLE PEOPLE_FLOW_RH.COMPETENCIA_CARGO
    ADD CONSTRAINT CHK_COMPCARGO_NIVEL CHECK (NIVEL_ESPERADO IS NULL OR NIVEL_ESPERADO BETWEEN 1 AND 5);

-- ============================
-- REEMBOLSOS
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.POLITICA_REEMBOLSO
    ADD CONSTRAINT CHK_PR_CATEGORIA CHECK (CATEGORIA IN ('alimentacao', 'transporte', 'hospedagem', 'material', 'treinamento', 'saude', 'outro'));

ALTER TABLE PEOPLE_FLOW_RH.POLITICA_REEMBOLSO
    ADD CONSTRAINT CHK_PR_VALOR_MAX CHECK (VALOR_MAX_POR_DIA IS NULL OR VALOR_MAX_POR_DIA >= 0);

ALTER TABLE PEOPLE_FLOW_RH.POLITICA_REEMBOLSO
    ADD CONSTRAINT CHK_PR_MOEDA CHECK (MOEDA IN ('BRL', 'USD', 'EUR'));

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO
    ADD CONSTRAINT CHK_RS_STATUS CHECK (STATUS IN ('pendente', 'em_analise', 'aprovado', 'reprovado', 'pago', 'cancelado'));

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_SOLICITACAO
    ADD CONSTRAINT CHK_RS_VALOR_TOTAL CHECK (VALOR_TOTAL >= 0);

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_ITEM
    ADD CONSTRAINT CHK_RI_VALOR CHECK (VALOR >= 0);

ALTER TABLE PEOPLE_FLOW_RH.REEMBOLSO_APROVACAO
    ADD CONSTRAINT CHK_RA_STATUS CHECK (STATUS IN ('aprovado', 'reprovado'));

-- ============================
-- FOLHA DE PAGAMENTO
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.RUBRICA
    ADD CONSTRAINT CHK_RUB_TIPO CHECK (TIPO IN ('provento', 'desconto'));

ALTER TABLE PEOPLE_FLOW_RH.FOLHA_EXECUCAO
    ADD CONSTRAINT CHK_FE_STATUS CHECK (STATUS IN ('aberta', 'em_calculo', 'calculada', 'em_aprovacao', 'aprovada', 'fechada'));

ALTER TABLE PEOPLE_FLOW_RH.FOLHA_ITEM
    ADD CONSTRAINT CHK_FI_QUANTIDADE CHECK (QUANTIDADE >= 0);

ALTER TABLE PEOPLE_FLOW_RH.FOLHA_ITEM
    ADD CONSTRAINT CHK_FI_VALOR CHECK (VALOR >= 0);

-- ============================
-- ESOCIAL
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.EVENTO_ESOCIAL
    ADD CONSTRAINT CHK_ESOCIAL_STATUS CHECK (STATUS IN ('gerado', 'enviado', 'processado', 'erro', 'rejeitado'));

-- ============================
-- WORKFLOW
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.INSTANCIA_WORKFLOW
    ADD CONSTRAINT CHK_IW_STATUS CHECK (STATUS IN ('em_andamento', 'concluido', 'cancelado', 'erro'));

ALTER TABLE PEOPLE_FLOW_RH.TAREFA_WORKFLOW
    ADD CONSTRAINT CHK_TW_STATUS CHECK (STATUS IN ('aberta', 'em_andamento', 'concluida', 'cancelada'));

-- ============================
-- NOTIFICAÇÕES
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.TEMPLATE_NOTIFICACAO
    ADD CONSTRAINT CHK_TN_CANAL CHECK (CANAL IN ('email', 'push', 'inapp'));

ALTER TABLE PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO
    ADD CONSTRAINT CHK_NE_CANAL CHECK (CANAL IN ('email', 'push', 'inapp'));

ALTER TABLE PEOPLE_FLOW_RH.NOTIFICACAO_ENVIO
    ADD CONSTRAINT CHK_NE_STATUS CHECK (STATUS IN ('pendente', 'enviado', 'erro'));

ALTER TABLE PEOPLE_FLOW_RH.DOCUMENTO_COLABORADOR
    ADD CONSTRAINT CHK_DOC_TIPO CHECK (TIPO IN ('contrato', 'atestado', 'exame', 'certidao', 'comprovante', 'documento', 'outro'));

ALTER TABLE PEOPLE_FLOW_RH.DOCUMENTO_COLABORADOR
    ADD CONSTRAINT CHK_DOC_TAMANHO CHECK (TAMANHO_BYTES >= 0);

ALTER TABLE PEOPLE_FLOW_RH.DOCUMENTO_COLABORADOR
    ADD CONSTRAINT CHK_DOC_VERSAO CHECK (VERSAO > 0);

-- ============================
-- SAÚDE OCUPACIONAL
-- ============================

ALTER TABLE PEOPLE_FLOW_RH.ASO
    ADD CONSTRAINT CHK_ASO_TIPO CHECK (TIPO IN ('admissional', 'periodico', 'retorno', 'mudanca', 'demissional'));

ALTER TABLE PEOPLE_FLOW_RH.ASO
    ADD CONSTRAINT CHK_ASO_DATAS CHECK (VALIDADE_ATE IS NULL OR VALIDADE_ATE >= REALIZADO_EM);

ALTER TABLE PEOPLE_FLOW_RH.EXAME_AGENDAMENTO
    ADD CONSTRAINT CHK_EXAME_STATUS CHECK (STATUS IN ('agendado', 'realizado', 'faltou', 'cancelado'));

ALTER TABLE PEOPLE_FLOW_RH.EXAME_AGENDAMENTO
    ADD CONSTRAINT CHK_EXAME_DATAS CHECK (REALIZADO_EM IS NULL OR REALIZADO_EM >= AGENDADO_EM);

