services:
  # Banco de dados PostgreSQL para produção
  postgres:
    image: postgres:16-alpine
    container_name: people-flow-postgres
    environment:
      POSTGRES_DB: people_flow_rh
      POSTGRES_USER: peopleflow
      POSTGRES_PASSWORD: peopleflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - people-flow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peopleflow -d people_flow_rh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Aplicação Spring Boot para produção
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: people-flow-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/people_flow_rh
      DATABASE_USERNAME: peopleflow
      DATABASE_PASSWORD: peopleflow
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - people-flow-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  people-flow-network:
    driver: bridge
