spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/people_flow_rh
    username: peopleflow
    password: peopleflow
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: "people_flow_rh"
  
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-disabled: false

logging:
  level:
    com.peopleflow: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: WARN
  file:
    name: /var/log/people-flow-api/application.log
