spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH}
    username: ${DATABASE_USERNAME:peopleflow}
    password: ${DATABASE_PASSWORD:peopleflow}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH}
    user: ${DATABASE_USERNAME:peopleflow}
    password: ${DATABASE_PASSWORD:peopleflow}
    schemas: app
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.peopleflow: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Configurações específicas de desenvolvimento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
