spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH}
    username: ${DATABASE_USERNAME:peopleflow}
    password: ${DATABASE_PASSWORD:peopleflow}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH}
    user: ${DATABASE_USERNAME:peopleflow}
    password: ${DATABASE_PASSWORD:peopleflow}
    schemas: app
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    com.peopleflow: INFO
    org.springframework.security: WARN
    org.flywaydb: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/people-flow-api/application.log
    max-size: 100MB
    max-history: 30

# Configurações específicas de produção
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Configurações de segurança para produção
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth/realms/peopleflow}
