spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/people_flow_rh
    username: ${DB_USERNAME:peopleflow}
    password: ${DB_PASSWORD:peopleflow}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: "people_flow_rh"
  
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-disabled: true

  # OAuth2 Resource Server - HABILITADO EM PRODUÇÃO
  security:
    oauth2:
      resourceserver:
        jwt:
          # Configurar com variáveis de ambiente
          issuer-uri: ${JWT_ISSUER_URI:https://auth.example.com/realms/peopleflow}
          jwk-set-uri: ${JWT_JWK_SET_URI:https://auth.example.com/realms/peopleflow/protocol/openid-connect/certs}

# Configurações da aplicação
app:
  security:
    enabled: ${SECURITY_ENABLED:true}  # Habilita segurança em produção

logging:
  level:
    com.peopleflow: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: WARN
  file:
    name: /var/log/people-flow-api/application.log
