spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/people_flow_rh
    username: peopleflow
    password: peopleflow
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: "people_flow_rh"
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: people_flow_rh
    default-schema: people_flow_rh

  # OAuth2 Resource Server - Desabilitado em DEV
  security:
    oauth2:
      resourceserver:
        jwt:
          # Descomentar e configurar quando tiver um servidor OAuth2 (Keycloak, Auth0, etc)
          # issuer-uri: http://localhost:8180/realms/peopleflow
          # jwk-set-uri: http://localhost:8180/realms/peopleflow/protocol/openid-connect/certs

# Configurações da aplicação
app:
  security:
    enabled: false  # Desabilita segurança em desenvolvimento

logging:
  level:
    com.peopleflow: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG