spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH
    username: peopleflow
    password: peopleflow
    driver-class-name: org.postgresql.Driver
  
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 20000
    idle-timeout: 300000
    max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: "PEOPLE_FLOW_RH"
  
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-disabled: false

logging:
  level:
    com.peopleflow: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
