spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH_DEV}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
  
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/PEOPLE_FLOW_RH_DEV}

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    com.peopleflow: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configurações específicas de desenvolvimento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
