-- ============================
-- ORGANIZAÇÃO / NÚCLEO
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CLIENTE (
    ID UUID PRIMARY KEY,
    NOME TEXT NOT NULL,
    CNPJ VARCHAR(18),
    STATUS TEXT NOT NULL DEFAULT 'ativo',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".EMPRESA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    CNPJ VARCHAR(18),
    INSCRICAO_ESTADUAL TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".UNIDADE (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    EMPRESA_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    CODIGO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".DEPARTAMENTO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    EMPRESA_ID UUID NOT NULL,
    UNIDADE_ID UUID,
    NOME TEXT NOT NULL,
    CODIGO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CENTRO_CUSTO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CODIGO TEXT NOT NULL,
    NOME TEXT NOT NULL,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- SEGURANÇA / RBAC
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".USUARIO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'ativo',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".PAPEL (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".PERMISSAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    RECURSO TEXT NOT NULL,
    ACAO TEXT NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".USUARIO_PAPEL (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    USUARIO_ID UUID NOT NULL,
    PAPEL_ID UUID NOT NULL,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".PAPEL_PERMISSAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    PAPEL_ID UUID NOT NULL,
    PERMISSAO_ID UUID NOT NULL
);

-- ============================
-- PESSOAS / COLABORADORES
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".COLABORADOR (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    EMPRESA_ID UUID NOT NULL,
    DEPARTAMENTO_ID UUID,
    CENTRO_CUSTO_ID UUID,
    NOME TEXT NOT NULL,
    CPF VARCHAR(14),
    MATRICULA VARCHAR(20),
    EMAIL TEXT,
    DATA_ADMISSAO DATE,
    DATA_DEMISSAO DATE,
    STATUS TEXT NOT NULL DEFAULT 'ativo',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".DEPENDENTE (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    PARENTESCO TEXT NOT NULL,
    DATA_NASCIMENTO DATE,
    CPF VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CONTA_BANCARIA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    BANCO TEXT NOT NULL,
    AGENCIA TEXT NOT NULL,
    CONTA TEXT NOT NULL,
    TIPO TEXT,
    PIX TEXT
);

-- ============================
-- JORNADA & CARGOS
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".JORNADA_TRABALHO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CARGA_SEMANAL_HORAS NUMERIC(5,2),
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CARGO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT,
    NIVEL TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".FAIXA_SALARIAL (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CARGO_ID UUID NOT NULL,
    FAIXA_MIN NUMERIC(14,2) NOT NULL,
    FAIXA_MAX NUMERIC(14,2) NOT NULL,
    MOEDA TEXT DEFAULT 'BRL',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".COLABORADOR_CARGO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    CARGO_ID UUID NOT NULL,
    CENTRO_CUSTO_ID UUID,
    SALARIO NUMERIC(14,2),
    INICIO DATE NOT NULL,
    FIM DATE,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- CONTRATOS
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CONTRATO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    JORNADA_ID UUID NOT NULL,
    CARGO_ID UUID NOT NULL,
    TIPO TEXT,
    REGIME TEXT,
    SALARIO_BASE NUMERIC(14,2),
    INICIO DATE NOT NULL,
    FIM DATE,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- PONTO
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".MARCACAO_PONTO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    DATA_HORA TIMESTAMPTZ NOT NULL,
    TIPO TEXT NOT NULL, -- entrada/saida
    ORIGEM TEXT,        -- kiosk/mobile/import
    LATITUDE NUMERIC(9,6),
    LONGITUDE NUMERIC(9,6),
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CALCULO_PONTO_DIA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    DATA DATE NOT NULL,
    HORAS_TRABALHADAS NUMERIC(6,2) DEFAULT 0,
    HORAS_EXTRAS NUMERIC(6,2) DEFAULT 0,
    BANCO_HORAS_SALDO NUMERIC(7,2) DEFAULT 0,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".AUSENCIA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    TIPO TEXT NOT NULL,  -- atestado, falta, justificada
    INICIO TIMESTAMPTZ NOT NULL,
    FIM TIMESTAMPTZ NOT NULL,
    JUSTIFICATIVA TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- FÉRIAS
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".FERIAS_SOLICITACAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    ABONO BOOLEAN DEFAULT FALSE,
    STATUS TEXT NOT NULL DEFAULT 'pendente',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".FERIAS_APROVACAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    SOLICITACAO_ID UUID NOT NULL,
    APROVADOR_USUARIO_ID UUID NOT NULL,
    STATUS TEXT NOT NULL, -- aprovado/reprovado
    OBSERVACAO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".FERIAS_SALDO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    DIAS_AQUISITIVOS INTEGER DEFAULT 0,
    DIAS_DISPONIVEIS INTEGER DEFAULT 0,
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- BENEFÍCIOS
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".PLANO_BENEFICIO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    TIPO TEXT NOT NULL, -- VT/VR/Saude/Outro
    NOME TEXT NOT NULL,
    FORNECEDOR TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".ADESAO_BENEFICIO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    PLANO_ID UUID NOT NULL,
    INICIO DATE NOT NULL,
    FIM DATE,
    CUSTO_MENSAL NUMERIC(12,2),
    COTA_COLABORADOR NUMERIC(12,2),
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- RECRUTAMENTO
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".VAGA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    TITULO TEXT NOT NULL,
    DESCRICAO TEXT,
    DEPARTAMENTO_ID UUID,
    LOCALIDADE TEXT,
    REMOTO BOOLEAN DEFAULT FALSE,
    STATUS TEXT NOT NULL DEFAULT 'aberta',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CANDIDATO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    EMAIL TEXT,
    TELEFONE TEXT,
    CPF VARCHAR(14),
    CONSENTIMENTO_LGPD BOOLEAN DEFAULT TRUE,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CANDIDATURA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    VAGA_ID UUID NOT NULL,
    CANDIDATO_ID UUID NOT NULL,
    DATA_CANDIDATURA DATE NOT NULL,
    ETAPA_ATUAL TEXT,
    STATUS TEXT NOT NULL DEFAULT 'em_analise',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".ENTREVISTA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CANDIDATURA_ID UUID NOT NULL,
    ENTREVISTADOR_USUARIO_ID UUID NOT NULL,
    AGENDADA_EM TIMESTAMPTZ NOT NULL,
    TIPO TEXT,
    FEEDBACK TEXT,
    RESULTADO TEXT, -- aprovado/reprovado/pendente
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- DESEMPENHO
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".CICLO_DESEMPENHO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".AVALIACAO_DESEMPENHO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CICLO_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    AVALIADOR_USUARIO_ID UUID NOT NULL,
    NOTA NUMERIC(4,2),
    COMENTARIOS TEXT,
    STATUS TEXT NOT NULL DEFAULT 'rascunho',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- OKR
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".OKR (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    TIPO TEXT NOT NULL, -- organizacional/equipe/pessoal
    TITULO TEXT NOT NULL,
    DESCRICAO TEXT,
    RESPONSAVEL_USUARIO_ID UUID,
    INICIO DATE,
    FIM DATE,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".OKR_RESULTADO_CHAVE (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    OKR_ID UUID NOT NULL,
    TITULO TEXT NOT NULL,
    UNIDADE TEXT, -- percentual/numero
    VALOR_ALVO NUMERIC(14,2),
    VALOR_ATUAL NUMERIC(14,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".OKR_CHECKIN (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    RESULTADO_CHAVE_ID UUID NOT NULL,
    REALIZADO_EM TIMESTAMPTZ NOT NULL,
    VALOR NUMERIC(14,2),
    COMENTARIO TEXT,
    USUARIO_ID UUID
);

-- ============================
-- PDI & COMPETÊNCIAS
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".PDI (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    CICLO_ID UUID,
    OBJETIVO TEXT NOT NULL,
    ACOES JSONB NOT NULL DEFAULT '[]'::jsonb,
    STATUS TEXT NOT NULL DEFAULT 'aberto',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".COMPETENCIA_CARGO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CARGO_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    NIVEL_ESPERADO INTEGER,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- REEMBOLSOS
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".POLITICA_REEMBOLSO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CATEGORIA TEXT NOT NULL,
    VALOR_MAX_POR_DIA NUMERIC(12,2),
    MOEDA TEXT DEFAULT 'BRL',
    EXIGE_DOCUMENTO BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".REEMBOLSO_SOLICITACAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    CATEGORIA TEXT NOT NULL,
    VALOR_TOTAL NUMERIC(14,2) NOT NULL DEFAULT 0,
    STATUS TEXT NOT NULL DEFAULT 'pendente',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".REEMBOLSO_ITEM (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    SOLICITACAO_ID UUID NOT NULL,
    DESCRICAO TEXT NOT NULL,
    VALOR NUMERIC(14,2) NOT NULL,
    DATA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".REEMBOLSO_APROVACAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    SOLICITACAO_ID UUID NOT NULL,
    APROVADOR_USUARIO_ID UUID NOT NULL,
    STATUS TEXT NOT NULL, -- aprovado/reprovado
    OBSERVACAO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- FOLHA DE PAGAMENTO
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".RUBRICA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    CODIGO TEXT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    TIPO TEXT NOT NULL, -- provento/desconto
    BASE_CALCULO JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".FOLHA_EXECUCAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COMPETENCIA DATE NOT NULL, -- use o dia 1 do mês
    STATUS TEXT NOT NULL DEFAULT 'aberta',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".FOLHA_ITEM (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    EXECUCAO_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    RUBRICA_ID UUID NOT NULL,
    QUANTIDADE NUMERIC(12,2) DEFAULT 1,
    VALOR NUMERIC(14,2) NOT NULL
);

-- ============================
-- ESOCIAL
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".EVENTO_ESOCIAL (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    TIPO TEXT NOT NULL, -- S-1000, S-2200, S-1200...
    REFERENCIA_ID UUID,
    STATUS TEXT NOT NULL DEFAULT 'gerado',
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".PAYLOAD_ESOCIAL (
    ID UUID PRIMARY KEY,
    EVENTO_ID UUID NOT NULL,
    VERSAO_LAYOUT TEXT,
    XML TEXT,
    RECIBO TEXT,
    PROTOCOLO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- WORKFLOW
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".DEFINICAO_WORKFLOW (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT,
    MODELO JSONB NOT NULL DEFAULT '{}'::jsonb,
    VERSAO INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".INSTANCIA_WORKFLOW (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    DEFINICAO_ID UUID NOT NULL,
    ENTIDADE TEXT NOT NULL,
    ENTIDADE_ID UUID NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'em_andamento',
    CONTEXTO JSONB NOT NULL DEFAULT '{}'::jsonb,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".TAREFA_WORKFLOW (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    INSTANCIA_ID UUID NOT NULL,
    RESPONSAVEL_USUARIO_ID UUID,
    ETAPA TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'aberta',
    PRAZO DATE,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".LOG_WORKFLOW (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    INSTANCIA_ID UUID NOT NULL,
    MENSAGEM TEXT NOT NULL,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- AUDITORIA
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".EVENTO_AUDITORIA (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    USUARIO_ID UUID,
    ENTIDADE TEXT NOT NULL,
    ENTIDADE_ID UUID,
    ACAO TEXT NOT NULL, -- create/update/delete
    DADOS JSONB NOT NULL DEFAULT '{}'::jsonb,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- NOTIFICAÇÕES
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".TEMPLATE_NOTIFICACAO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    NOME TEXT NOT NULL,
    CANAL TEXT NOT NULL CHECK (CANAL IN ('email','push','inapp')),
    ASSUNTO TEXT,
    CORPO TEXT NOT NULL,
    VARIAVEIS JSONB NOT NULL DEFAULT '{}'::jsonb,
    VERSAO INTEGER NOT NULL DEFAULT 1,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".NOTIFICACAO_ENVIO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    TEMPLATE_ID UUID,
    USUARIO_ID UUID,
    COLABORADOR_ID UUID,
    CANAL TEXT NOT NULL CHECK (CANAL IN ('email','push','inapp')),
    ASSUNTO TEXT,
    CORPO_RENDERIZADO TEXT NOT NULL,
    CONTEXTO JSONB NOT NULL DEFAULT '{}'::jsonb,
    STATUS TEXT NOT NULL DEFAULT 'pendente' CHECK (STATUS IN ('pendente','enviado','erro')),
    ERRO TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ENVIADO_EM TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".DOCUMENTO_COLABORADOR (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    TIPO TEXT NOT NULL,
    NOME_ARQUIVO TEXT NOT NULL,
    MIME_TYPE TEXT NOT NULL,
    TAMANHO_BYTES BIGINT NOT NULL CHECK (TAMANHO_BYTES >= 0),
    STORAGE_KEY TEXT NOT NULL,
    VERSAO INTEGER NOT NULL DEFAULT 1 CHECK (VERSAO > 0),
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================
-- SAÚDE OCUPACIONAL
-- ============================
CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".ASO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    TIPO TEXT NOT NULL CHECK (TIPO IN ('admissional','periodico','retorno','mudanca','demissional')),
    REALIZADO_EM DATE NOT NULL,
    VALIDADE_ATE DATE,
    CLINICA TEXT,
    RESULTADO TEXT,
    DOCUMENTO_ID UUID,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PEOPLE_FLOW_RH".EXAME_AGENDAMENTO (
    ID UUID PRIMARY KEY,
    CLIENTE_ID UUID NOT NULL,
    COLABORADOR_ID UUID NOT NULL,
    TIPO_EXAME TEXT NOT NULL,
    CLINICA TEXT,
    AGENDADO_EM TIMESTAMPTZ NOT NULL,
    REALIZADO_EM TIMESTAMPTZ,
    COMPARECEU BOOLEAN,
    STATUS TEXT NOT NULL DEFAULT 'agendado' CHECK (STATUS IN ('agendado','realizado','faltou','cancelado')),
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now(),
    ATUALIZADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

