-- ============================
-- ÍNDICES ÚNICOS DE INTEGRIDADE
-- ============================

-- Colaborador
CREATE UNIQUE INDEX IF NOT EXISTS UQ_COLABORADOR_CPF
    ON "PEOPLE_FLOW_RH".COLABORADOR (CLIENTE_ID, CPF);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_COLABORADOR_MATRICULA
    ON "PEOPLE_FLOW_RH".COLABORADOR (EMPRESA_ID, MATRICULA);

-- Empresa
CREATE UNIQUE INDEX IF NOT EXISTS UQ_EMPRESA_CNPJ
    ON "PEOPLE_FLOW_RH".EMPRESA (CLIENTE_ID, CNPJ);

-- Usuário
CREATE UNIQUE INDEX IF NOT EXISTS UQ_USUARIO_EMAIL
    ON "PEOPLE_FLOW_RH".USUARIO (CLIENTE_ID, EMAIL);

-- Candidato
CREATE UNIQUE INDEX IF NOT EXISTS UQ_CANDIDATO_CPF
    ON "PEOPLE_FLOW_RH".CANDIDATO (CLIENTE_ID, CPF);

-- ============================
-- ÍNDICES PARA BUSCA (FKs)
-- ============================

-- Organização
CREATE INDEX IF NOT EXISTS IDX_EMPRESA_CLIENTE ON "PEOPLE_FLOW_RH".EMPRESA(CLIENTE_ID);
CREATE INDEX IF NOT EXISTS IDX_UNIDADE_EMPRESA ON "PEOPLE_FLOW_RH".UNIDADE(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_DEPARTAMENTO_EMPRESA ON "PEOPLE_FLOW_RH".DEPARTAMENTO(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_DEPARTAMENTO_UNIDADE ON "PEOPLE_FLOW_RH".DEPARTAMENTO(UNIDADE_ID);

-- Segurança
CREATE INDEX IF NOT EXISTS IDX_USUARIO_CLIENTE ON "PEOPLE_FLOW_RH".USUARIO(CLIENTE_ID);
CREATE INDEX IF NOT EXISTS IDX_USUARIO_EMAIL ON "PEOPLE_FLOW_RH".USUARIO(EMAIL);

-- Pessoas / Contratos
CREATE INDEX IF NOT EXISTS IDX_COLAB_EMPRESA ON "PEOPLE_FLOW_RH".COLABORADOR(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_COLAB_DEPARTAMENTO ON "PEOPLE_FLOW_RH".COLABORADOR(DEPARTAMENTO_ID);
CREATE INDEX IF NOT EXISTS IDX_COLAB_CC ON "PEOPLE_FLOW_RH".COLABORADOR(CENTRO_CUSTO_ID);

CREATE INDEX IF NOT EXISTS IDX_DEPENDENTE_COLAB ON "PEOPLE_FLOW_RH".DEPENDENTE(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_CB_COLAB ON "PEOPLE_FLOW_RH".CONTA_BANCARIA(COLABORADOR_ID);

CREATE INDEX IF NOT EXISTS IDX_CONTRATO_COLAB ON "PEOPLE_FLOW_RH".CONTRATO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_CONTRATO_CARGO ON "PEOPLE_FLOW_RH".CONTRATO(CARGO_ID);

CREATE INDEX IF NOT EXISTS IDX_CC_COLAB ON "PEOPLE_FLOW_RH".COLABORADOR_CARGO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_CC_CARGO ON "PEOPLE_FLOW_RH".COLABORADOR_CARGO(CARGO_ID);

-- Ponto
CREATE INDEX IF NOT EXISTS IDX_MP_COLAB_DATA ON "PEOPLE_FLOW_RH".MARCACAO_PONTO(COLABORADOR_ID, DATA_HORA);
CREATE INDEX IF NOT EXISTS IDX_CPD_COLAB_DATA ON "PEOPLE_FLOW_RH".CALCULO_PONTO_DIA(COLABORADOR_ID, DATA);
CREATE INDEX IF NOT EXISTS IDX_AUS_COLAB_DATA ON "PEOPLE_FLOW_RH".AUSENCIA(COLABORADOR_ID, INICIO, FIM);

-- Férias
CREATE INDEX IF NOT EXISTS IDX_FS_COLAB ON "PEOPLE_FLOW_RH".FERIAS_SOLICITACAO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_FA_SOL ON "PEOPLE_FLOW_RH".FERIAS_APROVACAO(SOLICITACAO_ID);

-- Benefícios
CREATE INDEX IF NOT EXISTS IDX_AB_COLAB ON "PEOPLE_FLOW_RH".ADESAO_BENEFICIO(COLABORADOR_ID);

-- Recrutamento
CREATE INDEX IF NOT EXISTS IDX_CANDD_VAGA ON "PEOPLE_FLOW_RH".CANDIDATURA(VAGA_ID);
CREATE INDEX IF NOT EXISTS IDX_CANDD_CAND ON "PEOPLE_FLOW_RH".CANDIDATURA(CANDIDATO_ID);
CREATE INDEX IF NOT EXISTS IDX_ENT_CANDD ON "PEOPLE_FLOW_RH".ENTREVISTA(CANDIDATURA_ID);

-- Desempenho / OKR
CREATE INDEX IF NOT EXISTS IDX_AD_COLAB ON "PEOPLE_FLOW_RH".AVALIACAO_DESEMPENHO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_OKRRC_OKR ON "PEOPLE_FLOW_RH".OKR_RESULTADO_CHAVE(OKR_ID);
CREATE INDEX IF NOT EXISTS IDX_OKRC_RESULTADO ON "PEOPLE_FLOW_RH".OKR_CHECKIN(RESULTADO_CHAVE_ID);

CREATE INDEX IF NOT EXISTS IDX_PDI_COLAB ON "PEOPLE_FLOW_RH".PDI(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_COMP_CARGO ON "PEOPLE_FLOW_RH".COMPETENCIA_CARGO(CARGO_ID);

-- Reembolsos
CREATE INDEX IF NOT EXISTS IDX_RS_COLAB ON "PEOPLE_FLOW_RH".REEMBOLSO_SOLICITACAO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_RI_SOL ON "PEOPLE_FLOW_RH".REEMBOLSO_ITEM(SOLICITACAO_ID);

-- Folha
CREATE INDEX IF NOT EXISTS IDX_FI_EXECUCAO ON "PEOPLE_FLOW_RH".FOLHA_ITEM(EXECUCAO_ID);
CREATE INDEX IF NOT EXISTS IDX_FI_COLAB ON "PEOPLE_FLOW_RH".FOLHA_ITEM(COLABORADOR_ID);

-- eSocial
CREATE INDEX IF NOT EXISTS IDX_PESOCIAL_EVENTO ON "PEOPLE_FLOW_RH".PAYLOAD_ESOCIAL(EVENTO_ID);

-- Workflow
CREATE INDEX IF NOT EXISTS IDX_IW_DEFINICAO ON "PEOPLE_FLOW_RH".INSTANCIA_WORKFLOW(DEFINICAO_ID);
CREATE INDEX IF NOT EXISTS IDX_TW_INSTANCIA ON "PEOPLE_FLOW_RH".TAREFA_WORKFLOW(INSTANCIA_ID);
CREATE INDEX IF NOT EXISTS IDX_LW_INSTANCIA ON "PEOPLE_FLOW_RH".LOG_WORKFLOW(INSTANCIA_ID);

-- Auditoria
CREATE INDEX IF NOT EXISTS IDX_EA_USUARIO ON "PEOPLE_FLOW_RH".EVENTO_AUDITORIA(USUARIO_ID);

-- Notificações
CREATE INDEX IF NOT EXISTS IDX_NE_TEMPLATE ON "PEOPLE_FLOW_RH".NOTIFICACAO_ENVIO(TEMPLATE_ID);
CREATE INDEX IF NOT EXISTS IDX_NE_USUARIO ON "PEOPLE_FLOW_RH".NOTIFICACAO_ENVIO(USUARIO_ID);
CREATE INDEX IF NOT EXISTS IDX_NE_COLAB ON "PEOPLE_FLOW_RH".NOTIFICACAO_ENVIO(COLABORADOR_ID);

-- Saúde Ocupacional
CREATE INDEX IF NOT EXISTS IDX_ASO_COLAB ON "PEOPLE_FLOW_RH".ASO(COLABORADOR_ID);
CREATE INDEX IF NOT EXISTS IDX_EXAME_COLAB ON "PEOPLE_FLOW_RH".EXAME_AGENDAMENTO(COLABORADOR_ID);

