-- ============================
-- AUDITORIA
-- ============================

-- Tabela de log de auditoria
CREATE TABLE IF NOT EXISTS PEOPLE_FLOW_RH.AUDIT_LOG (
    ID UUID PRIMARY KEY,
    TENANT_ID TEXT NOT NULL,
    USUARIO_ID UUID,
    ENTIDADE TEXT NOT NULL,
    ENTIDADE_ID UUID,
    ACAO TEXT NOT NULL CHECK (ACAO IN ('CREATE','UPDATE','DELETE')),
    DADOS_ANTIGOS TEXT,
    DADOS_NOVOS TEXT,
    IP_ADDRESS TEXT,
    USER_AGENT TEXT,
    CRIADO_EM TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_audit_tenant_entidade ON PEOPLE_FLOW_RH.AUDIT_LOG(TENANT_ID, ENTIDADE);
CREATE INDEX IF NOT EXISTS idx_audit_entidade_id ON PEOPLE_FLOW_RH.AUDIT_LOG(ENTIDADE, ENTIDADE_ID);
CREATE INDEX IF NOT EXISTS idx_audit_criado_em ON PEOPLE_FLOW_RH.AUDIT_LOG(CRIADO_EM);
CREATE INDEX IF NOT EXISTS idx_audit_acao ON PEOPLE_FLOW_RH.AUDIT_LOG(ACAO);

-- Adicionar colunas de auditoria na tabela COLABORADOR
ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR 
ADD COLUMN IF NOT EXISTS CRIADO_POR TEXT DEFAULT 'system',
ADD COLUMN IF NOT EXISTS ATUALIZADO_POR TEXT DEFAULT 'system';

-- Atualizar registros existentes
UPDATE PEOPLE_FLOW_RH.COLABORADOR 
SET CRIADO_POR = 'system', ATUALIZADO_POR = 'system' 
WHERE CRIADO_POR IS NULL OR ATUALIZADO_POR IS NULL;
