-- ============================
-- Criar Sequence para COLABORADOR
-- ============================

CREATE SEQUENCE IF NOT EXISTS PEOPLE_FLOW_RH.COLABORADOR_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;

SELECT setval('PEOPLE_FLOW_RH.COLABORADOR_SEQ',
    COALESCE((SELECT MAX(ID) FROM PEOPLE_FLOW_RH.COLABORADOR), 0) + 1, 
    false);

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
    ALTER COLUMN ID DROP IDENTITY IF EXISTS;

ALTER TABLE PEOPLE_FLOW_RH.COLABORADOR
    ALTER COLUMN ID SET DEFAULT nextval('PEOPLE_FLOW_RH.COLABORADOR_SEQ');

ALTER SEQUENCE PEOPLE_FLOW_RH.COLABORADOR_SEQ
    OWNED BY PEOPLE_FLOW_RH.COLABORADOR.ID;

